# Generated by Django 2.2 on 2019-05-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=250)),
                ('article_text', models.CharField(max_length=5000)),
                ('article_summary', models.CharField(max_length=110)),
                ('article_author', models.CharField(max_length=250)),
                ('article_upvotes', models.IntegerField(default=0)),
                ('article_downvotes', models.IntegerField(default=0)),
                ('article_comments', models.IntegerField(default=0)),
                ('article_views', models.IntegerField(default=0)),
                ('image', models.FileField(default=None, upload_to='')),
            ],
        ),
    ]
