# Generated by Django 2.2.1 on 2019-05-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190505_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_tags',
            field=models.CharField(default='#code', max_length=250),
        ),
    ]
